# API config
UNDERLYING_SYMBOL = "TSLA"
UNDERLYING_ASSET_TYPE = "stock"
IB_HOST = "127.0.0.1"
IB_PORT = 7497
IB_CLIENT_ID = 0

# historical config
HISTORICAL_SYMBOL = "TSLA"
HISTORICAL_ASSET_TYPE = "stock"
HISTORICAL_DURATION = "2 D"
HISTORICAL_BAR_SIZE = "1 min"
HISTORICAL_TIMEOUT = 60

# Strategy selection
STRATEGY_NAME = "break1m"
SHOW_STRATEGY_SNAPSHOT = True

# EMA strategy parameters
EMA_FAST_PERIOD = 5
EMA_SLOW_PERIOD = 10

# SigHL strategy parameters
SIG_HL_LOOKBACK_TF = "4 hours"
SIG_HL_SESSION_ANCHOR = "09:30"
SIG_HL_ATR_PERIOD = 10
SIG_HL_ATR_MULTIPLIER = 1

# Break1M strategy parameters
BREAK_1M_SESSION_ANCHOR = "09:30"
BREAK_1M_PULLBACK_DOLLARS = 2.0
BREAK_1M_BOUNCE_DOLLARS = 2.0
BREAK_1M_BREAKOUT_BUFFER = 0.0
BREAK_1M_STOP_BUFFER = 0.05
BREAK_1M_REWARD_RISK_RATIO = 1.0
BREAK_1M_USE_CLOSE_CONFIRMATION = False

# Devlope config
# True = simulate only, False = send real orders
DRY_RUN_ORDERS = True

# True = send only one forced order per run, False = allow repeated signals
FORCE_SEND_ONCE = False

# True = allow new orders even when open orders exist
IGNORE_OPEN_ORDERS_FOR_TEST = True

# True = allow new orders even when positions exist
IGNORE_POSITIONS_FOR_TEST = True

USE_OPTION_MARKET_PRICE = True
OPTION_PRICE_TIMEOUT = 5
USE_OPTION_HISTORICAL_FALLBACK = True
OPTION_HISTORICAL_DURATION = "1 D"
OPTION_HISTORICAL_BAR_SIZE = "5 mins"
OPTION_HISTORICAL_TIMEOUT = 15
FALLBACK_OPTION_LIMIT_PRICE = 0.01

RUN_MODE = "forever"
# RUN_MODE = "once"

# Risk management
RISK_PER_TRADE_PERCENT = 1.0
MAX_CONTRACTS_PER_TRADE = 3
OPTION_MULTIPLIER = 100
MIN_ORDER_QUANTITY = 1
OPTION_POSITION_AVG_COST_INCLUDES_MULTIPLIER = True

# Exit management
ENABLE_EXIT_LOGIC = True
TAKE_PROFIT_PERCENT = 30
STOP_LOSS_PERCENT = 20
EXIT_ON_SELL_SIGNAL = True
