UNDERLYING_SYMBOL = "SPY"
UNDERLYING_ASSET_TYPE = "stock"

HISTORICAL_SYMBOL = "SPY"
HISTORICAL_ASSET_TYPE = "stock"
HISTORICAL_DURATION = "2 D"
HISTORICAL_BAR_SIZE = "30 mins"

DRY_RUN_ORDERS = False  
FORCE_SEND_ONCE = True
TEST_ORDER_QUANTITY = 1
TEST_ORDER_LIMIT_PRICE = 0.01
IGNORE_OPEN_ORDERS_FOR_TEST = False
IGNORE_POSITIONS_FOR_TEST = True 

RUN_MODE = "forever"
# RUN_MODE = "once"